notes/urls.py
from django.conf.urls import url
from django.urls import path, include

from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.NotesIndex.as_view(), name='index'),
    path('delete/<int:pk>/', views.DeleteNotesView.as_view(), name='remove_note'),
    path('update/<int:pk>/', views.UpdateNotesView.as_view(), name='update_note'),
    path('add/', views.CreateNotesView.as_view(), name='create_note'),
    ]

notesapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path, include

from notes import views
from notesapp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path("logout/", views.logout_request, name="logout"),
    url(r'^signup/$', views.signup, name='signup'),
]

notes/models.py
from django.db import models


# Create your models here.
class Notes(models.Model):
    title = models.CharField('Note title', max_length=50)
    text = models.CharField('Text', max_length=200)
    date = models.DateTimeField('Date', auto_now_add=True)

notes/forms.py
from django import forms
from django.forms import TextInput

from notes.models import Notes


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'text']

        widgets = {
            'title': TextInput(attrs={'placeholder': 'Name of note', 'class': 'form-control'}),
            'text': TextInput(attrs={'placeholder': 'Text of note', 'class': 'form-control'})
        }

notes/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from notes.forms import NotesForm
from notes.models import Notes


class NotesIndex(ListView):
    model = Notes
    context_object_name = 'all_notes'
    template_name = 'notes/notes_index.html'


class CreateNotesView(CreateView):
    model = Notes
    template_name = 'notes/notes_form.html'
    form_class = NotesForm

    def get_success_url(self):
        return reverse('notes:index')


class UpdateNotesView(UpdateView):
    model = Notes
    template_name = 'notes/notes_form.html'
    form_class = NotesForm

    def get_success_url(self):
        return reverse('notes:index')


class DeleteNotesView(DeleteView):
    model = Notes
    template_name = 'notes/notes_form.html'
    form_class = NotesForm

    def get_success_url(self):
        return reverse('notes:index')


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("login")


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('notes:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notes App</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>
<section class="hero is-primary is-fullheight">

    <div class="navbar-end">

        {% if user.is_authenticated %}
        <h4 class="navbar-item">Salut, {{ user.get_username }}!</h4>
        {% endif %}

        {% if not user.is_authenticated %}
        <a href="{% url 'login' %}" class="navbar-item">
            Login
        </a>

        <a href="{% url 'signup' %}" class="navbar-item">
            Sign Up
        </a>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'notes:index' %}" class="navbar-item">
            Notes
        </a>

        <a href="{% url 'logout' %}" class="navbar-item">
            Logout
        </a>
        {% endif %}

    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</section>
</body>

</html>

templates/notes/notes_form.html
{% extends 'base.html' %}
{% block content %}
     <form method="POST">
        {% csrf_token %}
         <div class="box">
            <div class="field">
                {% for field in form %}
                    <div class="form-control">{{ field.label }} {{ field }}
                    </div>
                    <div>{{ field.errors }}</div>
                {% endfor %}
            </div>
           <button type="submit" class="btn btn-info">Salveaza</button>
         </div>
     <form>
{% endblock %}

templates/notes/notes_index.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div><a class="btn btn-danger" href="{% url 'notes:create_note' %}">Add note</a></div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Note name</th>
            <th scope="col">Note date</th>
            <th scope="col">Text</th>
        </tr>
        </thead>
        <tbody>

        {% if all_notes %}
            {% for x in all_notes %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ x.title|upper }}</td>
                    <td>{{ x.date.date|upper }}</td>
                    <td>{{ x.text|upper }}</td>
                    <td><a class="btn btn-secondary" href="{% url 'notes:update_note' x.id %}">EDIT</a>
                        <a class="btn btn-secondary" href="{% url 'notes:remove_note' x.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="5" class="text-center">No data available</td></tr>
        {% endif %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
{% endblock %}